// <auto-generated />
namespace OwnYourDay.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class indexViews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(indexViews));
        
        string IMigrationMetadata.Id
        {
            get { return "202104222247487_indexViews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
